// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VSLab.Data;

#nullable disable

namespace VSLab.Migrations
{
    [DbContext(typeof(ChessDbContext))]
    [Migration("20230425060507_MigrationName")]
    partial class MigrationName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VSLab.Data.tblChessChampion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("ChessPlayerID")
                        .HasColumnType("integer");

                    b.Property<int>("ConsecutiveYears")
                        .HasColumnType("integer");

                    b.Property<int>("Current")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastTrophy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxRating")
                        .HasColumnType("integer");

                    b.Property<string>("Record")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("ChessPlayerID");

                    b.ToTable("tblChessChampions");
                });

            modelBuilder.Entity("VSLab.Data.tblChessParticipation", b =>
                {
                    b.Property<int>("ChessTournamentID")
                        .HasColumnType("integer");

                    b.Property<int>("ChessPlayerID")
                        .HasColumnType("integer");

                    b.Property<string>("DateSigned")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DurationPlayed")
                        .HasColumnType("text");

                    b.HasKey("ChessTournamentID", "ChessPlayerID");

                    b.HasIndex("ChessPlayerID");

                    b.ToTable("tblChessParticipations");
                });

            modelBuilder.Entity("VSLab.Data.tblChessPlayer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IsMaster")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("StartYear")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("tblChessPlayers");
                });

            modelBuilder.Entity("VSLab.Data.tblChessTournament", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumParticipants")
                        .HasColumnType("integer");

                    b.Property<int>("PrizeMoney")
                        .HasColumnType("integer");

                    b.Property<string>("Trophy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("tblChessTournaments");
                });

            modelBuilder.Entity("tblChessPlayertblChessTournament", b =>
                {
                    b.Property<int>("ChessPlayersID")
                        .HasColumnType("integer");

                    b.Property<int>("ChessTournamentsID")
                        .HasColumnType("integer");

                    b.HasKey("ChessPlayersID", "ChessTournamentsID");

                    b.HasIndex("ChessTournamentsID");

                    b.ToTable("tblChessPlayertblChessTournament");
                });

            modelBuilder.Entity("VSLab.Data.tblChessChampion", b =>
                {
                    b.HasOne("VSLab.Data.tblChessPlayer", "ChessPlayer")
                        .WithMany("ChessChampions")
                        .HasForeignKey("ChessPlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChessPlayer");
                });

            modelBuilder.Entity("VSLab.Data.tblChessParticipation", b =>
                {
                    b.HasOne("VSLab.Data.tblChessPlayer", "ChessPlayer")
                        .WithMany("PlayerParticipations")
                        .HasForeignKey("ChessPlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VSLab.Data.tblChessTournament", "ChessTournament")
                        .WithMany("TournamentParticipations")
                        .HasForeignKey("ChessTournamentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChessPlayer");

                    b.Navigation("ChessTournament");
                });

            modelBuilder.Entity("tblChessPlayertblChessTournament", b =>
                {
                    b.HasOne("VSLab.Data.tblChessPlayer", null)
                        .WithMany()
                        .HasForeignKey("ChessPlayersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VSLab.Data.tblChessTournament", null)
                        .WithMany()
                        .HasForeignKey("ChessTournamentsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VSLab.Data.tblChessPlayer", b =>
                {
                    b.Navigation("ChessChampions");

                    b.Navigation("PlayerParticipations");
                });

            modelBuilder.Entity("VSLab.Data.tblChessTournament", b =>
                {
                    b.Navigation("TournamentParticipations");
                });
#pragma warning restore 612, 618
        }
    }
}
